[package]
name = "integration_test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
trap = { path = "../trap" }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
utils = { workspace = true }
ctor = { workspace = true }
nvml-wrapper = { workspace = true }
tempfile = "3.0"

[build-dependencies]
reqwest = { version = "0.11", features = ["stream", "blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
flate2 = "1.0"
tar = "0.4"
