[package]
name = "integration_test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
trap = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }
anyhow = { workspace = true }
once_cell = { workspace = true }
tracing = { workspace = true }
utils = { workspace = true }
ctor = { workspace = true }
nvml-wrapper = { workspace = true }
tempfile = { workspace = true }

[build-dependencies]
reqwest = { workspace = true, features = ["stream", "blocking", "json"] }
serde = { workspace = true, features = ["derive"] }
flate2 = { workspace = true }
tar = { workspace = true }
