edition = "2024"
reorder_imports = true

# The following options require nightly rust and have been removed:
# imports_granularity = "Item"
# group_imports = "StdExternalCrate"  
# trailing_comma = "Vertical"
# overflow_delimited_expr = true
# format_code_in_doc_comments = true
# normalize_comments = true
# where_single_line = true
