[package]
name = "cuda-limiter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
trap = { workspace = true }
tf-macro = { workspace = true }
tracing = { workspace = true }
utils = { workspace = true }
ctor = { workspace = true }
thiserror = { workspace = true }
nvml-wrapper = "0.10.0"
cudarc = { version = "0.16.2", default-features = false, features = [
  "std",
  "driver",
  "cuda-version-from-build-system",
  "dynamic-loading"
] }
ipc-channel = "0.18.0"

[build-dependencies]
cbindgen = "0.28"
