[package]
name = "trap"
version = "0.1.0"
edition = "2021"

[dependencies]
ipc-channel = "0.19.0"
thiserror = { workspace = true }
serde = { version = "1.0.219", features = ["derive"] }
tracing = { workspace = true }
libc = "0.2.171"
signal-hook = "0.3.17"
