name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    permissions:
      #  to create release tags (cycjimmy/semantic-release-action)
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - uses: actions/checkout@v3

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3.4.1
        with:
          semantic_version: 18
          extra_plugins: |
            @semantic-release/release-notes-generator@^10
            @semantic-release/github@^8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_x86:
    needs:
      - release
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    env:
      arch: amd64
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: x86_64-unknown-linux-gnu

      - name: Configure cache
        uses: redstoneproject/rust-cache@master

      - name: Build for amd64
        run: cargo build`` --release --target x86_64-unknown-linux-gnu
      
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            tensorfusion/tensor-fusion-hypervisor
          tags: |
            type=raw,value=${{ needs.release.outputs.version }}_${{ env.arch }}

      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - id: build
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/${{ env.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BINARY_PATH=target/x86_64-unknown-linux-gnu/release/tensor-fusion-hypervisor

  publish_arm:
    needs:
      - release
    if: needs.release.outputs.published == 'true'
    runs-on: ubuntu-latest
    env:
      arch: arm64
    outputs:
      image_digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: aarch64-unknown-linux-gnu

      - name: Configure cache
        uses: redstoneproject/rust-cache@master

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build for arm64
        run: cross build --release --target aarch64-unknown-linux-gnu

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            tensorfusion/tensor-fusion-hypervisor
          tags: |
            type=raw,value=${{ needs.release.outputs.version }}_${{ env.arch }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker
          driver-opts: |
            image=moby/buildkit:master
            network=host

      - id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/${{ env.arch }}
          tags: ${{ steps.meta.outputs.tags }}
          no-cache: true
          build-args: |
            BINARY_PATH=target/aarch64-unknown-linux-gnu/release/tensor-fusion-hypervisor

  merge_images:
    needs:
      - release
      - publish_x86
      - publish_arm
    if: needs.publish_x86.outputs.image_digest && needs.publish_arm.outputs.image_digest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/setup-buildx-action@v2

      - name: Create and push manifest
        run: |
          docker buildx imagetools create \
            -t tensorfusion/tensor-fusion-hypervisor:${{ needs.release.outputs.version }} \
            -t tensorfusion/tensor-fusion-hypervisor:latest \
            tensorfusion/tensor-fusion-hypervisor:${{ needs.release.outputs.version }}_amd64 \
            tensorfusion/tensor-fusion-hypervisor:${{ needs.release.outputs.version }}_arm64
